name: Pipe Playwright

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install the allure-playwright
        run: npm i -D allure-playwright

      - name: Install the allure-commandline
        run: npm i -D allure-commandline    
        
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npm run test:allure
